### ISSUE TITLE
DFD Comments on NewDFD.MD

### ISSUE THREAD

**Issue by germonprez** [curtismarr/ISQA3420#5]
Curtis, 

Here are a few comments: 

1) The dataflow leaving sorted data needs to be labeled (Same with Ping and NSLookup)
2) Is verified string being written to the DB? Or is it triggering a database action? 
3) What is ping doing? 
4) Are their related datastores or external entities for Import Needed Files & NSLookup? 

Great start. 

MG

**Comment by curtismarr** [comment]
![dfd2](https://cloud.githubusercontent.com/assets/25205868/22398146/849b08fe-e547-11e6-9fda-2d4438c19b9a.PNG)

**Comment by curtismarr** [comment]
1. I added the labels for the dataflows missing information.
2.  After verify String, it uses the verified string to search the sorted data DB to see if the string is there or not. 
3. Ping and NSlookup both open a cmd process, and will perform a ping or nslookup (ping "stringname")(nslookup "stringname"). Ping will return if the ping succeeded or failed, nslookup returns the DNS results of the nslookup.
4. There is no relation from Import Needed Files and NSLookup. Import needed files will open the DB file that contains all of the information on current server names and IP addresses. NSLookup only runs nslookup on a server name or IP address through cmd. 

The program starts with "Request" which is where they would push the refresh button. Everything is then automatically done and saves relevant information into the sorted database. Once that is complete they enter a server name or IP address to search if it is being used, which is where it follows "search string": from USER, running three separate tests: Ping succeeds or fails, and DNS entries, and if it is in our database of servers.

The purposed of saving certain information into my own "Sorted Data" DB is for time efficiency. There is a lot of information, there are a total of roughly 24,000 lines searched. By storing this information into memory the user is able to search a string in roughly 3 seconds per search (after the initial sorting of about 3-4 minutes) instead of searching the imported files every time they do a search, which takes roughly 3-4 minutes per search. 

I'm not positive I have my DFD set up properly for what the program does, and welcome more input on how to improve it.

Curtis
