### ISSUE TITLE
DFD Comments Feb 14

### ISSUE THREAD

**Issue by germonprez** [curtismarr/ISQA3420#8]
Simple comments: 

I don't really see anyway for the manager to update or add new policy. 

Also, you have two processes named Verifier. If they are different, they should have different names. If they are the same, they should be combined. 

MG

**Comment by curtismarr** [comment]
The way I was thinking the manager would update or add a new policy was with the "Create/Edit Policy" process. It sends a policy name out to the process, which then checks the data base. If there is currently a policy with that name then it will update that policy with the given values, otherwise it will create a new policy. I have updated the second "Verify". I copied to create the second and apparently forgot to rename. 

I'm not positive if that's how the update and add new policy is supposed to work, however that was my thought process.
